erDiagram
    CUSTOMER ||--o{ ORDER : places
    CUSTOMER {
        int customerId
        string name
        string phone
    }
    ORDER {
        int orderId
        string deliveryAddress
    }
    ORDER ||--o{ ITEM : contains
    ITEM {
        int itemId
        string price
        string name
    }
%% add comments after that