sequenceDiagram
    Клиент->>UI: Хочу сделать заказ
    UI->>Клиент: Какие товары
    Клиент->>UI: Вот этих вот пони
    UI->>Клиент: На какой адрес
    Клиент->>UI: Вот мой адрес
    UI->>BE: создай заказ (адрес, список пони)
    BE->>DB: сохраняем заказ
    DB-->>UI: успех
    UI-->>Клиент: успех